# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: create-new-organization-repository
on:
  workflow_dispatch:
    inputs:
      name_of_new_repo:
        description: ''
        required: false
        default: new-project
      template_repo:
        description: 'https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/creating-a-template-repository'
        required: false
        default: vorprog/ui-template
env:
  TRUSTED_ACTORS: richardsnider
  ORGANIZATION: vorprog
  REPO_NAME: ${{ github.event.inputs.name_of_new_repo }}
  GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
  BRANCH_PROTECTION_RULES: |
    { 
      "required_pull_request_reviews": { 
        "require_code_owner_reviews": true 
      },
      "restrictions": { 
        "teams": [ "vorprog/admins" ]
      }
    }
jobs:
  create-repo:
    defaults:
      run:
        shell: bash -ex {0} # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#custom-shell
    runs-on: ubuntu-latest
    steps:
      - run: |
          export ADMIN_USERS=$(gh api /orgs/$ORGANIZATION/teams/admins/members --jq '.[].login')
          echo $ADMIN_USERS
          gh repo create $REPO_NAME  --confirm --enable-issues --template='${{ github.events.inputs.template }}'
          gh api /repos/$ORGANIZATION/$REPO_NAME/branches/main/protection -f body='$BRANCH_PROTECTION_RULES'
