# https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
name: create-new-organization-repository
on:
  workflow_dispatch:
    inputs:
      name_of_new_repo:
        description: ''
        required: false
        default: new-project
      template_repo:
        description: 'https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/creating-a-template-repository'
        required: false
        default: vorprog/ui-template
env:
  TRUSTED_ACTORS: richardsnider
  REPO_OWNER: vorprog
  REPO_NAME: ${{ github.event.inputs.name_of_new_repo }}
  GITHUB_AUTH_TOKEN: ${{ secrets.GITHUB_AUTH_TOKEN }}
  BRANCH_PROTECTION_RULES: |
    { 
      "required_pull_request_reviews": { 
        "require_code_owner_reviews": true 
      },
      "restrictions": { 
        "users": [ "richardsnider" ]
      }
    }
jobs:
  create-repo:
    if: contains('richardsnider,somenonexistantuser', github.actor)
    defaults:
      run:
        shell: bash -ex {0} # https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions#custom-shell
    runs-on: ubuntu-latest
    steps:
      - run: |
          gh repo create $REPO_NAME  --confirm --enable-issues --template ${{ github.events.inputs.template }}
          gh api /repos/$REPO_OWNER/$REPO_NAME/branches/main/protection -f body='$BRANCH_PROTECTION_RULES'
